default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: brendaneyre_development

test:
  <<: *default
  database: brendaneyre_test

production:
  <<: *default
  database: brendaneyre_production
  username: brendaneyre
  password: <%= ENV['BRENDANEYRE_DATABASE_PASSWORD'] %>
