require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ShowsController, type: :controller do
  let(:user) { create(:user) }

  before do
    sign_in user
  end

  # This should return the minimal set of attributes required to create a valid
  # Show. As you add validations to Show, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      dates: "October 31",
      venue: "Test Venue",
      location: "Test Location",
      link: "http://test.com",
      note: "Test Note",
      user_id: user.id
    }
  }

  let(:invalid_attributes) {
    {
      dates: nil,
      venue: nil,
      location: nil,
      link: nil,
      note: nil,
      user_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Show.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      show = Show.create! valid_attributes
      get :show, params: {id: show.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      show = Show.create! valid_attributes
      get :edit, params: {id: show.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Show" do
        expect {
          post :create, params: {show: valid_attributes}, session: valid_session
        }.to change(Show, :count).by(1)
      end

      it "redirects to the created show" do
        post :create, params: {show: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Show.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {show: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end

      it "does not create a new show" do
        expect {
          post :create, params: {show: invalid_attributes}, session: valid_session
        }.not_to change(Show, :count)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          dates: "November 1",
          venue: "Updated Venue",
          location: "Updated Location",
          link: "http://updated.com",
          note: "Updated Note"
        }
      }

      it "updates the requested show" do
        show = Show.create! valid_attributes
        put :update, params: {id: show.to_param, show: new_attributes}, session: valid_session
        show.reload
        expect(show.dates).to eq("November 1")
        expect(show.venue).to eq("Updated Venue")
        expect(show.location).to eq("Updated Location")
        expect(show.link).to eq("http://updated.com")
        expect(show.note).to eq("Updated Note")
      end

      it "redirects to the show" do
        show = Show.create! valid_attributes
        put :update, params: {id: show.to_param, show: valid_attributes}, session: valid_session
        expect(response).to redirect_to(show)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        show = Show.create! valid_attributes
        put :update, params: {id: show.to_param, show: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end

      it "does not update the show" do
        show = Show.create! valid_attributes
        original_attributes = show.attributes
        put :update, params: {id: show.to_param, show: invalid_attributes}, session: valid_session
        show.reload
        expect(show.attributes).to eq(original_attributes)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested show" do
      show = Show.create! valid_attributes
      expect {
        delete :destroy, params: {id: show.to_param}, session: valid_session
      }.to change(Show, :count).by(-1)
    end

    it "redirects to the shows list" do
      show = Show.create! valid_attributes
      delete :destroy, params: {id: show.to_param}, session: valid_session
      expect(response).to redirect_to(shows_url)
    end
  end

end
